env:
- name: SVELTE_APP_REMOTE_URL
  value: "http://myapp-dev-ns99-myapp-gruim.test"
- name: CONTAINER_NAME
  value: "myappdevns99myappgruim"

grases:
  gras:
    grapi:
      ssl: false
      buildimages:
        enabled: false
      deployimages:
        enabled: false
    gruim:
      ssl: false
      buildimages:
        enabled: false
      deployimages:
        enabled: false
ingress:
  enabled: true
  ssl: false
  hosts:
    - host: myapp.test
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

stage: dev
