env:
- name: DEV
  value: "true"
grases:
  gras:
    grapi:
      ssl: false
      dev: true
      buildimages:
        enabled: false
      deployimages:
        enabled: false
    gruim:
      ssl: false
      dev: true
      buildimages:
        enabled: false
      deployimages:
        enabled: false
ingress:
  enabled: true
  ssl: false
  hosts: []
  tls: []
stage: dev
