# Default values for myapp.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.


env: {}
# configuration for grapple ApplicationSet (gras)
gras-deploy:
  enabled: false
gras:
  enabled: true
  gras: {}
  grapi:
    # beimagetag: "v0.130"
    discoveredrepos: true
    ingress: true
    ssl: true
    sslissuer: letsencrypt-grapple-demo
    initContainers:
      - name: test
        spec:
          name: init-db
          image: mysql
          command:
            - bash
            - -c
            - sleep 5; while ! mysql -h $(host) -P $(port) -u $(username) -p$(password) -e "show databases;" 2>/dev/null; do echo -n .; sleep 2; done; mysql -h $(host) -P $(port) -u $(username) -p$(password) -e "CREATE DATABASE IF NOT EXISTS bexiodemo;"
    extraSecrets:
      - grpl-bexiodemo-conn-credential
      - bexio-config
    # volumes:
    #   - name: data
    #     emptyDir: {}
    #     # persistentVolumeClaim: 
    #     #   claimName: grapi-dbfile
    # volumeMounts:
    #   - name: data
    #     mountPath: /data
    # datasources:
    #   - name: "db"
    #     spec:
    #       memory:
    #         connector: "memory"
    #         name: "db"
    #         file: "/data/db.json"
    #         localStorage: "db"
    datasources:
      # - name: bexiodemo
      #   spec:
      #     mysql:
      #       database: bexiodemo
      #       host: $(host)
      #       name: bexiodemo
      #       password: $(password)
      #       port: $(port)
      #       url: ""
      #       user: $(username)
      - name: external
        content: '{"name":"external","connector":"rest","disableMigration":true,"baseURL":"/sample","options":{"headers":{"accept":"application/json","content-type":"application/json", "Authorization": "Bearer ${BEXIO_TOKEN}"}}, "operations":[]}'
    # models:
    #   - name: "personaldata"
    #     spec:
    #       name: personaldata
    #       base: Entity
    #       properties:
    #         id:
    #           type: number
    #           id: true
    #           required: true
    #           generated: true
    #         customerName:
    #           type: string
    #         customerLastname:
    #           type: string
    #         contactFirstName:
    #           type: string
    #         phone:
    #           type: string
    #         addressLine1:
    #           type: string
    #         addressLine2:
    #           type: string
    #         city:
    #           type: string
    #         state:
    #           type: string
    #         postalCode:
    #           type: string
    #         country:
    #           type: string
    #         creditLimit:
    #           type: number
    # repositories:
    #   - name: personaldata
    #     spec:
    #       datasource: bexiodemo
    #       model: personaldata
    # relations:
    #   - name: "employees"
    #     spec:
    #       relationName: "employees"
    #       sourceModel: "Customers"
    #       destinationModel: "Employees"
    #       foreignKeyName: "employeesId"
    #       relationType: "belongsTo"
    #       registerInclusionResolver: true
    # restcruds:
    #   - name: "bexiodemo"
    #     spec:
    #       datasource: "bexiodemo"
    controllers: []
    postpatches:
      - name: migrate-db
        content: bnBtIHJ1biBtaWdyYXRl
    prepatches:
      - name: create-bexio-data-config
        content: bWtkaXIgLXAgLi9jb25maWcgfHwgdHJ1ZQplY2hvICdbCiAgICB7CiAgICAgICAgImRzIjogImV4dGVybmFsIiwKICAgICAgICAibWV0aG9kIjogInBvc3QiLAogICAgICAgICJjb250cm9sbGVyIjogIkNvbnRhY3QiLAogICAgICAgICJhcGlVcmkiOiAiL2NvbnRhY3RzIiwKICAgICAgICAidXJsIjogImh0dHBzOi8vYXBpLmJleGlvLmNvbS8yLjAvY29udGFjdCIsCiAgICAgICAgImJvZHlQYXJhbXMiOiB7CiAgICAgICAgICAgICJ0eXBlIjogIm9iamVjdCIsCiAgICAgICAgICAgICJwcm9wZXJ0aWVzIjogewogICAgICAgICAgICAgICAgIm5yIjogewogICAgICAgICAgICAgICAgICAgICJ0eXBlIjogInN0cmluZyIKICAgICAgICAgICAgICAgIH0sCiAgICAgICAgICAgICAgICAiY29udGFjdF90eXBlX2lkIjogewogICAgICAgICAgICAgICAgICAgICJ0eXBlIjogIm51bWJlciIKICAgICAgICAgICAgICAgIH0sCiAgICAgICAgICAgICAgICAibmFtZV8xIjogewogICAgICAgICAgICAgICAgICAgICJ0eXBlIjogInN0cmluZyIsCiAgICAgICAgICAgICAgICAgICAgInJlcXVpcmVkIjogdHJ1ZQogICAgICAgICAgICAgICAgfSwKICAgICAgICAgICAgICAgICJuYW1lXzIiOiB7CiAgICAgICAgICAgICAgICAgICAgInR5cGUiOiAic3RyaW5nIgogICAgICAgICAgICAgICAgfSwKICAgICAgICAgICAgICAgICJzYWx1dGF0aW9uX2lkIjogewogICAgICAgICAgICAgICAgICAgICJ0eXBlIjogIm51bWJlciIKICAgICAgICAgICAgICAgIH0sCiAgICAgICAgICAgICAgICAic2FsdXRhdGlvbl9mb3JtIjogewogICAgICAgICAgICAgICAgICAgICJ0eXBlIjogIm51bWJlciIKICAgICAgICAgICAgICAgIH0sCiAgICAgICAgICAgICAgICAidGl0ZWxfaWQiOiB7CiAgICAgICAgICAgICAgICAgICAgInR5cGUiOiAibnVtYmVyIgogICAgICAgICAgICAgICAgfSwKICAgICAgICAgICAgICAgICJhZGRyZXNzIjogewogICAgICAgICAgICAgICAgICAgICJ0eXBlIjogInN0cmluZyIKICAgICAgICAgICAgICAgIH0sCiAgICAgICAgICAgICAgICAicG9zdGNvZGUiOiB7CiAgICAgICAgICAgICAgICAgICAgInR5cGUiOiAic3RyaW5nIgogICAgICAgICAgICAgICAgfSwKICAgICAgICAgICAgICAgICJjaXR5IjogewogICAgICAgICAgICAgICAgICAgICJ0eXBlIjogInN0cmluZyIKICAgICAgICAgICAgICAgIH0sCiAgICAgICAgICAgICAgICAiY291bnRyeV9pZCI6IHsKICAgICAgICAgICAgICAgICAgICAidHlwZSI6ICJudW1iZXIiCiAgICAgICAgICAgICAgICB9LAogICAgICAgICAgICAgICAgIm1haWwiOiB7CiAgICAgICAgICAgICAgICAgICAgInR5cGUiOiAic3RyaW5nIgogICAgICAgICAgICAgICAgfSwKICAgICAgICAgICAgICAgICJtYWlsX3NlY29uZCI6IHsKICAgICAgICAgICAgICAgICAgICAidHlwZSI6ICJzdHJpbmciCiAgICAgICAgICAgICAgICB9LAogICAgICAgICAgICAgICAgInBob25lX2ZpeGVkIjogewogICAgICAgICAgICAgICAgICAgICJ0eXBlIjogInN0cmluZyIKICAgICAgICAgICAgICAgIH0sCiAgICAgICAgICAgICAgICAicGhvbmVfZml4ZWRfc2Vjb25kIjogewogICAgICAgICAgICAgICAgICAgICJ0eXBlIjogInN0cmluZyIKICAgICAgICAgICAgICAgIH0sCiAgICAgICAgICAgICAgICAicGhvbmVfbW9iaWxlIjogewogICAgICAgICAgICAgICAgICAgICJ0eXBlIjogInN0cmluZyIKICAgICAgICAgICAgICAgIH0sCiAgICAgICAgICAgICAgICAiZmF4IjogewogICAgICAgICAgICAgICAgICAgICJ0eXBlIjogInN0cmluZyIKICAgICAgICAgICAgICAgIH0sCiAgICAgICAgICAgICAgICAidXJsIjogewogICAgICAgICAgICAgICAgICAgICJ0eXBlIjogInN0cmluZyIKICAgICAgICAgICAgICAgIH0sCiAgICAgICAgICAgICAgICAic2t5cGVfbmFtZSI6IHsKICAgICAgICAgICAgICAgICAgICAidHlwZSI6ICJzdHJpbmciCiAgICAgICAgICAgICAgICB9LAogICAgICAgICAgICAgICAgInJlbWFya3MiOiB7CiAgICAgICAgICAgICAgICAgICAgInR5cGUiOiAic3RyaW5nIgogICAgICAgICAgICAgICAgfSwKICAgICAgICAgICAgICAgICJsYW5ndWFnZV9pZCI6IHsKICAgICAgICAgICAgICAgICAgICAidHlwZSI6ICJudW1iZXIiCiAgICAgICAgICAgICAgICB9LAogICAgICAgICAgICAgICAgImNvbnRhY3RfZ3JvdXBfaWRzIjogewogICAgICAgICAgICAgICAgICAgICJ0eXBlIjogInN0cmluZyIKICAgICAgICAgICAgICAgIH0sCiAgICAgICAgICAgICAgICAiY29udGFjdF9icmFuY2hfaWRzIjogewogICAgICAgICAgICAgICAgICAgICJ0eXBlIjogInN0cmluZyIKICAgICAgICAgICAgICAgIH0sCiAgICAgICAgICAgICAgICAidXNlcl9pZCI6IHsKICAgICAgICAgICAgICAgICAgICAidHlwZSI6ICJudW1iZXIiLAogICAgICAgICAgICAgICAgICAgICJyZXF1aXJlZCI6IHRydWUKICAgICAgICAgICAgICAgIH0sCiAgICAgICAgICAgICAgICAib3duZXJfaWQiOiB7CiAgICAgICAgICAgICAgICAgICAgInR5cGUiOiAibnVtYmVyIiwKICAgICAgICAgICAgICAgICAgICAicmVxdWlyZWQiOiB0cnVlCiAgICAgICAgICAgICAgICB9CiAgICAgICAgICAgIH0KICAgICAgICB9LAogICAgICAgICJjcmVhdGVNb2RlbCI6IHRydWUsCiAgICAgICAgIm1vZGVsTmFtZSI6ICJDb250YWN0IiwKICAgICAgICAiYWRkaXRpb25hbFByb3BlcnRpZXMiOiB7CiAgICAgICAgICAgICJpZCI6IHsKICAgICAgICAgICAgICAgICJ0eXBlIjogIm51bWJlciIsCiAgICAgICAgICAgICAgICAicmVxdWlyZWQiOiBmYWxzZSwKICAgICAgICAgICAgICAgICJpZCI6IHRydWUKICAgICAgICAgICAgfSwKICAgICAgICAgICAgInVwZGF0ZWRfYXQiOiB7CiAgICAgICAgICAgICAgICAidHlwZSI6ICJzdHJpbmciCiAgICAgICAgICAgIH0sCiAgICAgICAgICAgICJwcm9maWxlX2ltYWdlIjogewogICAgICAgICAgICAgICAgInR5cGUiOiAic3RyaW5nIgogICAgICAgICAgICB9CiAgICAgICAgfSwKICAgICAgICAiYXBpRnVuY3Rpb24iOiAiY3JlYXRlQmV4aW9Db250YWN0IiwKICAgICAgICAicmVzcG9uc2VzIjogewogICAgICAgICAgICAiNDIyIjogewogICAgICAgICAgICAgICAgImRlc2NyaXB0aW9uIjogIlZhbGlkYXRpb24gZXJyb3IiLAogICAgICAgICAgICAgICAgInNjaGVtYSI6IHsKICAgICAgICAgICAgICAgICAgICAidHlwZSI6ICJvYmplY3QiLAogICAgICAgICAgICAgICAgICAgICJwcm9wZXJ0aWVzIjogewogICAgICAgICAgICAgICAgICAgICAgICAiZXJyb3JfY29kZSI6IHsKICAgICAgICAgICAgICAgICAgICAgICAgICAgICJ0eXBlIjogIm51bWJlciIKICAgICAgICAgICAgICAgICAgICAgICAgfSwKICAgICAgICAgICAgICAgICAgICAgICAgIm1lc3NhZ2UiOiB7CiAgICAgICAgICAgICAgICAgICAgICAgICAgICAidHlwZSI6ICJudW1iZXIiCiAgICAgICAgICAgICAgICAgICAgICAgIH0KICAgICAgICAgICAgICAgICAgICB9CiAgICAgICAgICAgICAgICB9CiAgICAgICAgICAgIH0sCiAgICAgICAgICAgICIyMDEiOiB7CiAgICAgICAgICAgICAgICAic2NoZW1hIjogewogICAgICAgICAgICAgICAgICAgICJ0eXBlIjogIm9iamVjdCIsCiAgICAgICAgICAgICAgICAgICAgIm1vZGVsIjogIkNvbnRhY3QiCiAgICAgICAgICAgICAgICB9CiAgICAgICAgICAgIH0KICAgICAgICB9CiAgICB9LAogICAgewogICAgICAgICJkcyI6ICJleHRlcm5hbCIsCiAgICAgICAgImNvbnRyb2xsZXIiOiAiQ29udGFjdCIsCiAgICAgICAgImFwaVVyaSI6ICIvY29udGFjdHMiLAogICAgICAgICJ1cmwiOiAiaHR0cHM6Ly9hcGkuYmV4aW8uY29tLzIuMC9jb250YWN0IiwKICAgICAgICAiYXBpRnVuY3Rpb24iOiAiZmV0Y2hCZXhpb0NvbnRhY3QiLAogICAgICAgICJjb3VudCI6IHRydWUsCiAgICAgICAgInF1ZXJ5UGFyYW1zIjogewogICAgICAgICAgICAid2hlcmUiOiB7CiAgICAgICAgICAgICAgICAidHlwZSI6ICJvYmplY3QiCiAgICAgICAgICAgIH0KICAgICAgICB9LAogICAgICAgICJtb2RlbE5hbWUiOiAiQ29udGFjdCIsCiAgICAgICAgInJlc3BvbnNlcyI6IHsKICAgICAgICAgICAgIjIwMCI6IHsKICAgICAgICAgICAgICAgICJzY2hlbWEiOiB7CiAgICAgICAgICAgICAgICAgICAgInR5cGUiOiAiYXJyYXkiLAogICAgICAgICAgICAgICAgICAgICJtb2RlbCI6ICJDb250YWN0IgogICAgICAgICAgICAgICAgfQogICAgICAgICAgICB9CiAgICAgICAgfQogICAgfSwKICAgIHsKICAgICAgICAiZHMiOiAiZXh0ZXJuYWwiLAogICAgICAgICJjb250cm9sbGVyIjogIkNvbnRhY3QiLAogICAgICAgICJhcGlVcmkiOiAiL2NvbnRhY3RzL3tpZH0iLAogICAgICAgICJ1cmwiOiAiaHR0cHM6Ly9hcGkuYmV4aW8uY29tLzIuMC9jb250YWN0L3tpZH0iLAogICAgICAgICJhcGlGdW5jdGlvbiI6ICJmZXRjaFNpbmdsZUJleGlvQ29udGFjdCIsCiAgICAgICAgImRlc2NyaXB0aW9uIjogImZldGNoIHNpbmdsZSBjb250ZWN0cy4iLAogICAgICAgICJtb2RlbE5hbWUiOiAiQ29udGFjdCIsCiAgICAgICAgInBhdGhQYXJhbXMiOiB7CiAgICAgICAgICAgICJpZCI6IHsKICAgICAgICAgICAgICAgICJ0eXBlIjogIm51bWJlciIKICAgICAgICAgICAgfQogICAgICAgIH0sCiAgICAgICAgInF1ZXJ5UGFyYW1zIjogewogICAgICAgICAgICAic2hvd19hcmNoaXZlZCI6IHsKICAgICAgICAgICAgICAgICJ0eXBlIjogImJvb2xlYW4iCiAgICAgICAgICAgIH0KICAgICAgICB9LAogICAgICAgICJyZXNwb25zZXMiOiB7CiAgICAgICAgICAgICIyMDAiOiB7CiAgICAgICAgICAgICAgICAic2NoZW1hIjogewogICAgICAgICAgICAgICAgICAgICJ0eXBlIjogIm9iamVjdCIsCiAgICAgICAgICAgICAgICAgICAgIm1vZGVsIjogIkNvbnRhY3QiCiAgICAgICAgICAgICAgICB9CiAgICAgICAgICAgIH0KICAgICAgICB9CiAgICB9LAogICAgewogICAgICAgICJkcyI6ICJleHRlcm5hbCIsCiAgICAgICAgIm1ldGhvZCI6ICJwYXRjaCIsCiAgICAgICAgImNvbnRyb2xsZXIiOiAiQ29udGFjdCIsCiAgICAgICAgImFwaVVyaSI6ICIvY29udGFjdHMve2lkfSIsCiAgICAgICAgImRlc2NyaXB0aW9uIjogInVwZGF0ZSBjb250ZWN0cy4iLAogICAgICAgICJyZXBsYWNlQnlJZCI6IHRydWUsCiAgICAgICAgInVwZGF0ZUFsbCI6IHRydWUsCiAgICAgICAgInNpbmdsZUZldGNoTWV0aG9kTmFtZSI6ICJmZXRjaFNpbmdsZUJleGlvQ29udGFjdCIsCiAgICAgICAgImZldGNoTWV0aG9kTmFtZSI6ICJmZXRjaEJleGlvQ29udGFjdCIsCiAgICAgICAgInVybCI6ICJodHRwczovL2FwaS5iZXhpby5jb20vMi4wL2NvbnRhY3Qve2lkfSIsCiAgICAgICAgInBhdGhQYXJhbXMiOiB7CiAgICAgICAgICAgICJpZCI6IHsKICAgICAgICAgICAgICAgICJ0eXBlIjogIm51bWJlciIKICAgICAgICAgICAgfQogICAgICAgIH0sCiAgICAgICAgImJvZHlQYXJhbXMiOiB7CiAgICAgICAgICAgICJ0eXBlIjogIm9iamVjdCIsCiAgICAgICAgICAgICJwcm9wZXJ0aWVzIjogewogICAgICAgICAgICAgICAgIm5yIjogewogICAgICAgICAgICAgICAgICAgICJ0eXBlIjogInN0cmluZyIKICAgICAgICAgICAgICAgIH0sCiAgICAgICAgICAgICAgICAiY29udGFjdF90eXBlX2lkIjogewogICAgICAgICAgICAgICAgICAgICJ0eXBlIjogIm51bWJlciIKICAgICAgICAgICAgICAgIH0sCiAgICAgICAgICAgICAgICAibmFtZV8xIjogewogICAgICAgICAgICAgICAgICAgICJ0eXBlIjogInN0cmluZyIsCiAgICAgICAgICAgICAgICAgICAgInJlcXVpcmVkIjogdHJ1ZQogICAgICAgICAgICAgICAgfSwKICAgICAgICAgICAgICAgICJuYW1lXzIiOiB7CiAgICAgICAgICAgICAgICAgICAgInR5cGUiOiAic3RyaW5nIgogICAgICAgICAgICAgICAgfSwKICAgICAgICAgICAgICAgICJzYWx1dGF0aW9uX2lkIjogewogICAgICAgICAgICAgICAgICAgICJ0eXBlIjogIm51bWJlciIKICAgICAgICAgICAgICAgIH0sCiAgICAgICAgICAgICAgICAic2FsdXRhdGlvbl9mb3JtIjogewogICAgICAgICAgICAgICAgICAgICJ0eXBlIjogIm51bWJlciIKICAgICAgICAgICAgICAgIH0sCiAgICAgICAgICAgICAgICAidGl0ZWxfaWQiOiB7CiAgICAgICAgICAgICAgICAgICAgInR5cGUiOiAibnVtYmVyIgogICAgICAgICAgICAgICAgfSwKICAgICAgICAgICAgICAgICJhZGRyZXNzIjogewogICAgICAgICAgICAgICAgICAgICJ0eXBlIjogInN0cmluZyIKICAgICAgICAgICAgICAgIH0sCiAgICAgICAgICAgICAgICAicG9zdGNvZGUiOiB7CiAgICAgICAgICAgICAgICAgICAgInR5cGUiOiAic3RyaW5nIgogICAgICAgICAgICAgICAgfSwKICAgICAgICAgICAgICAgICJjaXR5IjogewogICAgICAgICAgICAgICAgICAgICJ0eXBlIjogInN0cmluZyIKICAgICAgICAgICAgICAgIH0sCiAgICAgICAgICAgICAgICAiY291bnRyeV9pZCI6IHsKICAgICAgICAgICAgICAgICAgICAidHlwZSI6ICJudW1iZXIiCiAgICAgICAgICAgICAgICB9LAogICAgICAgICAgICAgICAgIm1haWwiOiB7CiAgICAgICAgICAgICAgICAgICAgInR5cGUiOiAic3RyaW5nIgogICAgICAgICAgICAgICAgfSwKICAgICAgICAgICAgICAgICJtYWlsX3NlY29uZCI6IHsKICAgICAgICAgICAgICAgICAgICAidHlwZSI6ICJzdHJpbmciCiAgICAgICAgICAgICAgICB9LAogICAgICAgICAgICAgICAgInBob25lX2ZpeGVkIjogewogICAgICAgICAgICAgICAgICAgICJ0eXBlIjogInN0cmluZyIKICAgICAgICAgICAgICAgIH0sCiAgICAgICAgICAgICAgICAicGhvbmVfZml4ZWRfc2Vjb25kIjogewogICAgICAgICAgICAgICAgICAgICJ0eXBlIjogInN0cmluZyIKICAgICAgICAgICAgICAgIH0sCiAgICAgICAgICAgICAgICAicGhvbmVfbW9iaWxlIjogewogICAgICAgICAgICAgICAgICAgICJ0eXBlIjogInN0cmluZyIKICAgICAgICAgICAgICAgIH0sCiAgICAgICAgICAgICAgICAiZmF4IjogewogICAgICAgICAgICAgICAgICAgICJ0eXBlIjogInN0cmluZyIKICAgICAgICAgICAgICAgIH0sCiAgICAgICAgICAgICAgICAidXJsIjogewogICAgICAgICAgICAgICAgICAgICJ0eXBlIjogInN0cmluZyIKICAgICAgICAgICAgICAgIH0sCiAgICAgICAgICAgICAgICAic2t5cGVfbmFtZSI6IHsKICAgICAgICAgICAgICAgICAgICAidHlwZSI6ICJzdHJpbmciCiAgICAgICAgICAgICAgICB9LAogICAgICAgICAgICAgICAgInJlbWFya3MiOiB7CiAgICAgICAgICAgICAgICAgICAgInR5cGUiOiAic3RyaW5nIgogICAgICAgICAgICAgICAgfSwKICAgICAgICAgICAgICAgICJsYW5ndWFnZV9pZCI6IHsKICAgICAgICAgICAgICAgICAgICAidHlwZSI6ICJudW1iZXIiCiAgICAgICAgICAgICAgICB9LAogICAgICAgICAgICAgICAgImNvbnRhY3RfZ3JvdXBfaWRzIjogewogICAgICAgICAgICAgICAgICAgICJ0eXBlIjogInN0cmluZyIKICAgICAgICAgICAgICAgIH0sCiAgICAgICAgICAgICAgICAiY29udGFjdF9icmFuY2hfaWRzIjogewogICAgICAgICAgICAgICAgICAgICJ0eXBlIjogInN0cmluZyIKICAgICAgICAgICAgICAgIH0sCiAgICAgICAgICAgICAgICAidXNlcl9pZCI6IHsKICAgICAgICAgICAgICAgICAgICAidHlwZSI6ICJudW1iZXIiLAogICAgICAgICAgICAgICAgICAgICJyZXF1aXJlZCI6IHRydWUKICAgICAgICAgICAgICAgIH0sCiAgICAgICAgICAgICAgICAib3duZXJfaWQiOiB7CiAgICAgICAgICAgICAgICAgICAgInR5cGUiOiAibnVtYmVyIiwKICAgICAgICAgICAgICAgICAgICAicmVxdWlyZWQiOiB0cnVlCiAgICAgICAgICAgICAgICB9CiAgICAgICAgICAgIH0KICAgICAgICB9LAogICAgICAgICJtb2RlbE5hbWUiOiAiQ29udGFjdCIsCiAgICAgICAgImFwaUZ1bmN0aW9uIjogImVkaXRCZXhpb0NvbnRhY3QiLAogICAgICAgICJyZXNwb25zZXMiOiB7CiAgICAgICAgICAgICI0MjIiOiB7CiAgICAgICAgICAgICAgICAiZGVzY3JpcHRpb24iOiAiVmFsaWRhdGlvbiBlcnJvciIsCiAgICAgICAgICAgICAgICAic2NoZW1hIjogewogICAgICAgICAgICAgICAgICAgICJ0eXBlIjogIm9iamVjdCIsCiAgICAgICAgICAgICAgICAgICAgInByb3BlcnRpZXMiOiB7CiAgICAgICAgICAgICAgICAgICAgICAgICJlcnJvcl9jb2RlIjogewogICAgICAgICAgICAgICAgICAgICAgICAgICAgInR5cGUiOiAibnVtYmVyIgogICAgICAgICAgICAgICAgICAgICAgICB9LAogICAgICAgICAgICAgICAgICAgICAgICAibWVzc2FnZSI6IHsKICAgICAgICAgICAgICAgICAgICAgICAgICAgICJ0eXBlIjogIm51bWJlciIKICAgICAgICAgICAgICAgICAgICAgICAgfQogICAgICAgICAgICAgICAgICAgIH0KICAgICAgICAgICAgICAgIH0KICAgICAgICAgICAgfSwKICAgICAgICAgICAgIjIwMCI6IHsKICAgICAgICAgICAgICAgICJzY2hlbWEiOiB7CiAgICAgICAgICAgICAgICAgICAgInR5cGUiOiAib2JqZWN0IiwKICAgICAgICAgICAgICAgICAgICAibW9kZWwiOiAiQ29udGFjdCIKICAgICAgICAgICAgICAgIH0KICAgICAgICAgICAgfQogICAgICAgIH0KICAgIH0sCiAgICB7CiAgICAgICAgImRzIjogImV4dGVybmFsIiwKICAgICAgICAibWV0aG9kIjogImRlbCIsCiAgICAgICAgImNvbnRyb2xsZXIiOiAiQ29udGFjdCIsCiAgICAgICAgImFwaVVyaSI6ICIvY29udGFjdHMve2lkfSIsCiAgICAgICAgInVybCI6ICJodHRwczovL2FwaS5iZXhpby5jb20vMi4wL2NvbnRhY3Qve2lkfSIsCiAgICAgICAgInBhdGhQYXJhbXMiOiB7CiAgICAgICAgICAgICJpZCI6IHsKICAgICAgICAgICAgICAgICJ0eXBlIjogIm51bWJlciIKICAgICAgICAgICAgfQogICAgICAgIH0sCiAgICAgICAgImFwaUZ1bmN0aW9uIjogImRlbGV0ZUJleGlvQ29udGFjdCIsCiAgICAgICAgIm1vZGVsTmFtZSI6ICJDb250YWN0IiwKICAgICAgICAicmVzcG9uc2VzIjogewogICAgICAgICAgICAiMjAwIjogewogICAgICAgICAgICAgICAgInNjaGVtYSI6IHsKICAgICAgICAgICAgICAgICAgICAidHlwZSI6ICJvYmplY3QiLAogICAgICAgICAgICAgICAgICAgICJwcm9wZXJ0aWVzIjogewogICAgICAgICAgICAgICAgICAgICAgICAic3VjY2VzcyI6IHsKICAgICAgICAgICAgICAgICAgICAgICAgICAgICJ0eXBlIjogImJvb2xlYW4iCiAgICAgICAgICAgICAgICAgICAgICAgIH0KICAgICAgICAgICAgICAgICAgICB9CiAgICAgICAgICAgICAgICB9CiAgICAgICAgICAgIH0KICAgICAgICB9CiAgICB9Cl0nID4gLi9jb25maWcvYmV4aW8tb3B0aW9ucy5qc29u
  gruim:
    # uiimagetag: "0.1.38"
    ssl: true
    sslissuer: letsencrypt-grapple-demo
    style: '{"colors":{"primary":{"DEFAULT":"#34344A","fg":"#fff"},"accent":{"DEFAULT":"#CC5A71","fg":"#fff"}}}'
    config: ""
    additionalpackages: ""
    custommodules: []
replicaCount: 1
image:
  repository: grpl/grapple-template-pr
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "0.1.45.pr-33"
imagetest:
  repository: apptest
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""
imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""
podAnnotations: {}
podSecurityContext: {}
# fsGroup: 2000

securityContext: {}
# capabilities:
#   drop:
#   - ALL
# readOnlyRootFilesystem: true
# runAsNonRoot: true
# runAsUser: 1000

service:
  type: ClusterIP
  port: 80
ingress:
  enabled: true
  className: ""
  annotations: {}
  # kubernetes.io/ingress.class: nginx
  # kubernetes.io/tls-acme: "true"
  # hosts:
  #   - host: chart-example.local
  #     paths:
  #       - path: /
  #         pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local
resources: {}
# We usually recommend not to specify default resources and to leave this as a conscious
# choice for the user. This also increases chances charts run on environments with little
# resources, such as Minikube. If you do want to specify resources, uncomment the following
# lines, adjust them as necessary, and remove the curly braces after 'resources:'.
# limits:
#   cpu: 100m
#   memory: 128Mi
# requests:
#   cpu: 100m
#   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80
nodeSelector: {}
tolerations: []
affinity: {}
