version: v2beta1
imports:
  - git: https://bitbucket.org/wolke7-patrick/grapple-central-build-pipeline.git

name: grpl-bexio-demo
vars:
  APP_NAME: "bexio-demo"
  IMAGE_REGISTRY: "grpl"
  IMAGE_REPO: "grpl-bexio-demo"
  APP_IMAGE: "${IMAGE_REGISTRY}/${IMAGE_REPO}"
  TEST_IMAGE: "${APP_IMAGE}-test"
  MODULES_IMAGE: "${APP_IMAGE}-modules"
  # DATA_IMAGE / Dockerfile.data can be added when local seed data is needed.
  TEST_DOCKERFILE: "Dockerfile.test"
  MODULES_DOCKERFILE: "Dockerfile.modules"
  TAG: "devspace"
  MULTIARCH: "false"
  # here you need to define the images to build and their coresponding dockerfiles
  IMAGES: "${APP_IMAGE}:${TAG} ${TEST_IMAGE}:${TAG} ${MODULES_IMAGE}:${TAG}"
  DOCKERFILES: "${APP_DOCKERFILE} ${TEST_DOCKERFILE} ${MODULES_DOCKERFILE}"
  APP_DOCKERFILE: "Dockerfile"

# This is a list of `pipelines` that DevSpace can execute (you can define your own)
functions:
  patch-values-file-modules: |-
    task patch-values-file-modules
  patch-values-file: |-
    task patch-values-file
  patch-values-file-patches-only: |-
    task patch-values-file-patches-only
  reset-values-file: |-
    task reset-values-file

pipelines:
  build: |-
    if [ "${MULTIARCH}" = "true" ]; then
      buildx-multiarch
    else
      build_images --all
    fi
  build-app: |-
    build_images app
  # This is the pipeline for the main command: `devspace dev` (or `devspace run-pipeline dev`)
  dev:
    run: |-
      export STAGE=devspace
      patch-values-file-patches-only
      # 1. Deploy any projects this project needs (see "dependencies")
      run_dependencies --all
      # 2. Ensure pull secrets
      ensure_pull_secrets --all
      patch-values-file-modules
      # 3. Build, tag (git commit hash) and push the application and modules images
      build_images app modules -t $(git describe --always)
      # Deploy Helm charts and manifests specified under "deployments"
      create_deployments --all
      reset-values-file
      wait-for-deployment ${APP_NAME}-gras-grapi 600
      start_dev grapi &
      start_dev gruim &
      # Start frontend development mode (see "dev" section)
      start_dev app
  # You can run this pipeline via `devspace deploy` (or `devspace run-pipeline deploy`)
  deploy:
    run: |-
      export STAGE=devspace
      patch-values-file
      # 1. Deploy any projects this project needs (see "dependencies")
      run_dependencies --all
      # 2. Ensure pull secrets
      ensure_pull_secrets --all
      patch-values-file-modules
      # 3. Build, tag (git commit hash) and push the application and modules images
      build_images app modules -t $(git describe --always)
      # Deploy Helm charts and manifests specified under "deployments"
      create_deployments --all
      reset-values-file

# This is a list of `images` that DevSpace can build for this project
# We recommend to skip image building during development (devspace dev) as much as possible
images:
  app:
    image: "${APP_IMAGE}"
    dockerfile: ${APP_DOCKERFILE}
    # Implemented for the Bitbucket pipeline with the profiles at the end of this file
    buildKit:
      args: [--platform, "linux/amd64,linux/arm64"]
  test:
    image: "${TEST_IMAGE}"
    dockerfile: ${TEST_DOCKERFILE}
    # Implemented for the Bitbucket pipeline with the profiles at the end of this file
    buildKit:
      args: [--platform, "linux/amd64,linux/arm64"]
  modules:
    image: "${MODULES_IMAGE}"
    dockerfile: ${MODULES_DOCKERFILE}
    # Implemented for the Bitbucket pipeline with the profiles at the end of this file
    buildKit:
      args: [--platform, "linux/amd64,linux/arm64"]

# This is a list of `deployments` that DevSpace can create for this project
deployments:
  app:
    # This deployment uses `helm` but you can also define `kubectl` deployments or kustomizations
    helm:
      releaseName: ${APP_NAME}
      # We are deploying this project with the Helm chart you provided
      chart:
        name: ./chart
      # Under `values` we can define the values for this Helm chart used during `helm install/upgrade`
      # You may also use `valuesFiles` to load values from files, e.g. valuesFiles: ["values.yaml"]
      valuesFiles:
        - ./chart/values.yaml
        - ./chart/values-dev.yaml
        - ./chart/values-devspace.yaml
      values:
        image:
          repository: ${runtime.images.app.image}
          tag: ${runtime.images.app.tag}

# This is a list of `dev` containers that are based on the containers created by your deployments
dev:
  app:
    # Search for the container that runs this image
    labelSelector:
      app.kubernetes.io/instance: ${APP_NAME}
      app.kubernetes.io/name: grpl-bexio-demo
    # Replace the container image with this dev-optimized image
    devImage: ${runtime.images.app}
    env:
      - name: DEV
        value: "true"
    # Sync files between the local filesystem and the development container
    sync:
      - path: ./
        excludePaths:
          - node_modules
          - chart
          - data
          - dist
          - config
          - grases
        uploadExcludeFile: .dockerignore
        disableDownload: true
    # Open a terminal and use the following command to start it
    terminal:
      command: dos2unix ./rebuild.sh && /bin/sh ./rebuild.sh
    # Inject a lightweight SSH server into the container (so your IDE can connect to the remote dev env)
    ssh:
      enabled: true
    # Make the following commands from my local machine available inside the dev container
    proxyCommands:
      - command: devspace
      - command: kubectl
      - command: helm
      - gitCredentials: true
    # Forward the following ports to be able access your application via localhost
    ports:
      - port: "4000"
    # Open the following URLs once they return an HTTP status code other than 502 or 503
    open:
      - url: http://localhost:4000
  gruim:
    # Search for the container that runs this image
    labelSelector:
      app.kubernetes.io/name: gruim
      grpl.io/resourceName: ${APP_NAME}-gras-gruim
    # Replace the container image with this dev-optimized image
    devImage: docker.io/grpl/gruim:0.3.62
    env:
      - name: DEV
        value: "true"
      # NODE_OPTIONS ipv4first need to be defined for fixing the ipv4 resolution in webpack http-proxy-middleware:
      # https://github.com/chimurai/http-proxy-middleware/issues/705
      # important for k3d deployments
      - name: NODE_OPTIONS
        value: "--dns-result-order=ipv4first"
    # Sync files between the local filesystem and the development container
    sync:
      - path: ./grases/gras2/gruim/custommodules/.:/usr/src/app/src/lib/custom-components/.
    # Forward the following ports to be able access your application via localhost
    ports:
      - port: "8080:8080"
    # Open the following URLs once they return an HTTP status code other than 502 or 503
    open:
      - url: http://localhost:8080
  grapi:
    # Search for the container that runs this image
    labelSelector:
      app.kubernetes.io/name: grapi
      grpl.io/resourceName: ${APP_NAME}-gras-grapi
    # Replace the container image with this dev-optimized image
    devImage: docker.io/grpl/loopback:0.4.24
    env:
      - name: DEV
        value: "true"
      - name: CustomControllerDir
        value: "injections"
      - name: CustomControllerDirs
        value: '{"controllerDirs":"injections"}'
      - name: CustomServiceDirs
        value: '{"serviceDirs":"serviceproviders"}'
    # Sync files between the local filesystem and the development container
    sync:
      - path: ./grases/gras/grapi/injections/:/home/node/app/src/injections/
        disableDownload: true
      - path: ./grases/gras/grapi/serviceproviders/:/home/node/app/src/serviceproviders/
        disableDownload: true
      - path: ./grases/gras/grapi/modules/:/opt/custom-modules/
        disableDownload: true
        excludePaths:
          - "**/node_modules/"
          - "**/index.js"
          - "**/index.d.ts"
          - "**/package.json"
          - "**/package-lock.json"
        onUpload:
          exec:
            - command: bash
              args:
                - -c
                - |
                  ./scripts/07.5-install-modules.sh
                  pkill -f "node ." || true
    # Forward the following ports to be able access your application via localhost
    ports:
      - port: "3000:3000"
    # Open the following URLs once they return an HTTP status code other than 502 or 503
    open:
      - url: http://localhost:3000

# Use the `commands` section to define repeatable dev workflows for this project
commands:
  gruim:
    command: |-
      devspace enter --label-selector "app.kubernetes.io/name=gruim,grpl.io/resourceName=${APP_NAME}-gras-gruim" gruim $@
  grapi:
    command: |-
      devspace enter --label-selector "app.kubernetes.io/name=grapi,grpl.io/resourceName=${APP_NAME}-gras-grapi" grapi $@
  migrate-db:
    command: |-
      devspace enter --label-selector "app.kubernetes.io/name=grapi,grpl.io/resourceName=${APP_NAME}-gras-grapi" npm run build && \
      devspace enter --label-selector "app.kubernetes.io/name=grapi,grpl.io/resourceName=${APP_NAME}-gras-grapi" npm run migrate

# Define dependencies to other projects with a devspace.yaml
# dependencies:
#   api:
#     git: https://...  # Git-based dependencies
#     tag: v1.0.0
#   ui:
#     path: ./ui        # Path-based dependencies (for monorepos)
# localRegistry:
#   enabled: false
# localRegistry:
#   localbuild: truede
profiles:
  - name: bitbucket
    activation:
      - vars:
          CI: true
    patches:
      - op: remove
        path: images.app.buildKit
      - op: remove
        path: images.test.buildKit
      - op: remove
        path: images.modules.buildKit
  - name: remove-buildkit-on-linux
    activation:
      - vars:
          DEVSPACE_LINUX: "true"
    patches:
      - op: remove
        path: images.app.buildKit
      - op: remove
        path: images.test.buildKit
      - op: remove
        path: images.modules.buildKit
